[package]
name = "rucredstash"
version = "0.1.0"
authors = ["Sibi Prabakaran <sibi@psibi.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
rusoto_core = "0.41.0"
rusoto_dynamodb = "0.41.0"
rusoto_ec2 = "0.41.0"
rusoto_kms = "0.41.0"
ring = "0.16.9"
aes-ctr = "0.3.0"
bytes = "0.4.12"

[[bin]]
name = "rucredstash"
path = "src/main.rs"
