jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stable:
        RUSTUP_TOOLCHAIN: stable
    maxParallel: 4
  steps:
   - script: |
       curl -sSf -o rustup-init.exe https://win.rustup.rs
       rustup-init.exe -y --profile minimal --default-toolchain none
       set PATH=%PATH%;%USERPROFILE%\.cargo\bin
       rustup toolchain install %RUSTUP_TOOLCHAIN%
       rustup default %RUSTUP_TOOLCHAIN%
       echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
     displayName: "Install rust (windows)"
   - script: |
       cargo test --lib
       cargo test --doc
     displayName: 'Test'
