jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stable:
        RUST_CI_VERSION: stable
    maxParallel: 4
  steps:
   - template: azure-install-rust.yml
     parameters:
       rust_version: $RUST_CI_VERSION
  - script: |
      cargo test --lib
      cargo test --doc
    displayName: 'Test'
